title: Navin Mohan
email: myfullname81@gmail.com
description: >- 
  Navin's personal website and blog.
baseurl: "" 
url: "https://navinmohan.com" 
twitter_username: navin_mohan_
github_username:  navin-mohan
linkedin_username: navin-mohan

header_pages:
  - blog-home.md
  - my-list.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title