# The URL the site will be built for
base_url = "https://navinmohan.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "terminus"

title = "Navin Mohan"

author = "Navin Mohan"



[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]

google_analytics_id = "G-3MBG0NNR14"

main_menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
]

socials = [
    { name = "github", url = "https://github.com/navin-mohan" },
    { name = "linkedin", url = "https://www.linkedin.com/in/navin-mohan/" },
    # { name = "medium", url = "https://medium.com/@navinmohan" },
    # { name = "substack", url = "https://navinmohan.substack.com/" },
]